name: phonehome-development
services:
    database:
        image: postgres:14.12-alpine
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", $DB_DATABASE, "-U", $DB_USERNAME ]
        ports:
            - "5432:5432"
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
    app:
        pull_policy: never
        build:
            dockerfile: containers/php/Dockerfile
            target: development
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        hostname: app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes: &app-volumes
            - .:/var/www/html
            - home:/home/www-data
    node:
        build:
            dockerfile: containers/node/Dockerfile
            target: development
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        volumes: *app-volumes
        ports:
            - "5173:5173"
        command: ["tail", "-f", "/dev/null"]
        stop_signal: SIGKILL
    web:
        pull_policy: never
        build:
            dockerfile: containers/nginx/Dockerfile
        depends_on:
            - app
        volumes: *app-volumes
        ports:
            - "80:80"
        environment:
            FPM_URL: app
            FPM_PORT: 9000

    adminer:
        image: adminer:4.8.1
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: database

    testing:
        profiles:
            - testing
        pull_policy: never
        build:
            dockerfile: containers/php/Dockerfile
            target: testing
            cache_from:
                - type=gha
        depends_on:
            - database
        secrets:
            -   source: env_file
                target: /var/www/html/.env
        environment:
            APP_ENV: testing
            APP_KEY: base64:jobMaruKa1iNGS74JK7PGywi5zGWdgIo0HoMG0B+hrY=

volumes:
    database: { }
    home: { }

secrets:
    env_file:
        file: .env
