name: phonehome-prod
services:
    database:
        image: postgres:14.15-alpine
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "phonehome", "-U", "phonehome" ]
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: phonehome
            POSTGRES_USER: phonehome
            POSTGRES_PASSWORD: phonehome
    app:
        image: ghcr.io/nethserver/phonehome-server-app:latest
        volumes:
            - bootstrap:/var/www/html/bootstrap
            - storage:/var/www/html/storage
        env_file:
            - .env
    scheduler:
        extends:
            service: app
        environment:
            FPM_URL: app
            FPM_PORT: 9000
        command: [ "crond", "-f", "-l", "2" ]
    web:
        image: ghcr.io/nethserver/phonehome-server-web:latest
        healthcheck:
            test: [ "CMD", "curl", "--fail", "--silent", "--output", "/dev/null", "http://localhost/status" ]
        environment:
            FPM_URL: app
            FPM_PORT: 9000

volumes:
    database: { }
    bootstrap: { }
    storage: { }
