name: Build
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_call:
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
env:
  REGISTRY: ghcr.io
  REPOSITORY: tbaile/phonehome
  TAG: ${{ github.ref_name }}
jobs:
  build-image:
    name: Build ${{ matrix.image }} image and push
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image:
          - app
          - web
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create new buildx builder
        uses: docker/setup-buildx-action@v2

      - name: Generate tags
        uses: docker/metadata-action@v4
        id: meta
        with:
          bake-target: ${{ matrix.image }}-release
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/bake-action@v2.3.0
        with:
          targets: ${{ matrix.image }}-release
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          set: |
            *.platform=linux/amd64

  build-deploy:
    name: Build NS8 deploy image
    runs-on: ubuntu-22.04
    needs: build-image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate tags
        uses: docker/metadata-action@v4
        id: meta
        with:
          bake-target: ns8-release
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: when rolling releases are a thing, remember to update the PHONEHOME_TAG
      - name: Build image with buildah
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          LABELS: ${{ steps.meta.outputs.labels }}
          ARGS: PHONEHOME_TAG=${{ github.ref_name }}
        working-directory: deploy/ns8
        run: |
          ./build-images.sh

      - name: Push image to registry
        run: |
          for tag in '${{ steps.meta.outputs.tags }}'; do
            podman push "$tag"
          done
