name: Development CI
on:
  push:
    branches:
      - master
jobs:
  application-testing:
    uses: ./.github/workflows/test.yml
  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - application-testing
    strategy:
      matrix:
        image: [ app, web ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: tbaile/phonehome-${{ matrix.image }}
          bake-target: ${{ matrix.image }}-release
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch
      - name: Build and push
        uses: docker/bake-action@v2.2.0
        with:
          targets: ${{ matrix.image }}-release
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
