name: Development Pipeline
on:
  push:
    branches:
      - "master"
      - "!renovate/**"
env:
  REPOSITORY: tbaile/phonehome
jobs:
  test-app-image:
    uses: ./.github/workflows/test.yml

  build-and-push-images:
    uses: ./.github/workflows/build.yml
    needs:
      - test-app-image
    secrets: inherit
