name: Testing
on:
  pull_request:
  workflow_call:
jobs:
  test-app-image:
    name: Test app image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create new buildx builder
        uses: docker/setup-buildx-action@v2

      - name: Generate Image Metadata
        uses: docker/metadata-action@v4
        id: cache-from-tag
        with:
          images: |
            ghcr.io/${{ github.repository }}-app
          tags: |
            type=ref,event=branch
            type=raw,enable=${{ github.event_name == 'pull_request' }},value=${{ github.base_ref }}
          flavor: |
            latest=false
            suffix=-cache

      - uses: docker/bake-action@v3.1.0
        with:
          files: |
            ./docker-bake.hcl
          targets: testing
          set: |
            *.platform=linux/amd64
            *.cache-from=type=registry,ref=${{ steps.cache-from-tag.outputs.tags }}
