name: Testing
on:
  pull_request:
  workflow_call:
jobs:
  test-app-image:
    name: Test app image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create new buildx builder
        uses: docker/setup-buildx-action@v2

      - name: Set REPOSITORY environment variable
        run: |
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - uses: docker/bake-action@v2.3.0
        env:
          TAG: ${{ github.ref_name }}
        with:
          files: |
            ./docker-bake.hcl
          targets: testing
          set: |
            *.platform=linux/amd64
