name: Testing
on:
  pull_request:
  workflow_call:
env:
  REPOSITORY: ${{ github.repository }}
  TAG: ${{ github.ref_name }}
jobs:
  test-app-image:
    name: Test app image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create new buildx builder
        uses: docker/setup-buildx-action@v2

      - uses: docker/bake-action@v2.3.0
        with:
          files: |
            ./docker-bake.hcl
          targets: testing
          set: |
            *.platform=linux/amd64
